[package]
name = "pull_requests_ui"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/pull_requests_ui.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
collections.workspace = true
editor.workspace = true
fs.workspace = true
futures.workspace = true
git.workspace = true
gpui.workspace = true
language.workspace = true
log.workspace = true
menu.workspace = true
project.workspace = true
pull_requests.workspace = true
schemars.workspace = true
serde.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true
zed_actions.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }